# Generated by Django 5.0.6 on 2024-05-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_user_is_online_user_last_login_end_user_login_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'db_table': 'league_round_team',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='league.team')),
            ],
            options={
                'db_table': 'league_tournament',
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('teams', models.ManyToManyField(through='league.RoundTeam', to='league.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='league.tournament')),
            ],
            options={
                'db_table': 'league_tournament_round',
            },
        ),
        migrations.AddField(
            model_name='roundteam',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.tournamentround'),
        ),
    ]
